Repository pplg-smk-metland/metschoo-library, pull requests merged in 2024-11, with the labels that each got.

#51 menambahkan ikon kembali
  components/CTA.vue
  components/PageHeader.vue
  pages/admin/buku/[isbn].vue
  pages/admin/buku/tambah.vue
  pages/buku/[isbn].vue
  pages/profil/edit.vue
  pages/profil/keamanan.vue
Labels: enhancement

#53 Explicit imports
  components/signIn/SignInForm.vue
  pages/profil/edit.vue
Labels: enhancement

#58 Create feature-request issue template
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation

#62 Admin
  pages/admin/buku/index.vue
  pages/admin/index.vue
  pages/admin/peminjaman.vue
  pages/admin/pengguna/[id].vue
  pages/admin/pengguna/index.vue
Labels: enhancement

#60 Buku image
  components/BookItem.vue
  components/profile/ProfileBook.vue
  components/profile/ProfileHistoryBook.vue
  components/wishlist/WishlistBook.vue
  composables/index.ts
  package.json
  pages/buku/[isbn].vue
  supabase/migrations/20241106152752_add_buku_image_col.sql
  types/database.types.ts
  utils/index.ts
Labels: enhancement

#65 fix: edit profile not working
  .github/workflows/lint.yml
  .nvmrc
  package.json
  pages/profil/edit.vue
  stores/auth.ts
Labels: bug

#69 Buku forms
  assets/primevue/inputnumber.css
  composables/index.ts
  nuxt.config.ts
  pages/admin/buku/[isbn].vue
  pages/admin/buku/tambah.vue
  utils/index.ts
Labels: enhancement

#70 Admin UI
  components/admin/AdminSidebar.vue
  lib/peminjaman.ts
  nuxt.config.ts
  pages/admin/buku/index.vue
  pages/admin/index.vue
  pages/admin/peminjaman.vue
  pages/admin/pengguna/index.vue
  pnpm-lock.yaml
  types/index.ts
  utils/index.ts
Labels: enhancement
